// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sprint_3.Data;

#nullable disable

namespace Sprint_3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518141415_AdicionarTabelasRestantes")]
    partial class AdicionarTabelasRestantes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sprint_3.Models.Aluno", b =>
                {
                    b.Property<long>("idealuno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("idealuno"));

                    b.Property<string>("cpf")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime?>("dataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("matricula")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("nomaluno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("idealuno");

                    b.ToTable("alunos");
                });

            modelBuilder.Entity("Sprint_3.Models.Disciplina", b =>
                {
                    b.Property<long>("idedisciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("idedisciplina"));

                    b.Property<string>("cargahoraria")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ementa")
                        .HasColumnType("longtext");

                    b.Property<string>("nomemateria")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("idedisciplina");

                    b.ToTable("disciplinas");
                });

            modelBuilder.Entity("Sprint_3.Models.MatriculaDisciplina", b =>
                {
                    b.Property<long>("idMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("idMatricula"));

                    b.Property<int?>("frequencia")
                        .HasColumnType("int");

                    b.Property<long>("idealuno")
                        .HasColumnType("bigint");

                    b.Property<long>("ideturma")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("nota")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("idMatricula");

                    b.ToTable("matriculas_disciplinas");
                });

            modelBuilder.Entity("Sprint_3.Models.Professor", b =>
                {
                    b.Property<long>("ideprofessor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ideprofessor"));

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nomeprofessor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ideprofessor");

                    b.ToTable("professores");
                });

            modelBuilder.Entity("Sprint_3.Models.Turma", b =>
                {
                    b.Property<long>("idturma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("idturma"));

                    b.Property<long>("idedisciplina")
                        .HasColumnType("bigint");

                    b.Property<long>("ideprofessor")
                        .HasColumnType("bigint");

                    b.HasKey("idturma");

                    b.ToTable("turmas");
                });

            modelBuilder.Entity("Sprint_3.Models.Usuario", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .HasColumnType("longtext");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
